# Generated by `rjournal_pdf_article()` using `knitr::purl()`: do not edit by hand
# Please edit climatekit.Rmd to modify this file

## ----setup, include = FALSE---------------------------------------------------
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE,
                      fig.align = "center", out.width = "100%")


## ----precip, fig.cap = "Annual precipitation indices for New York Central Park (GHCND station USW00094728), 1950 to 2024. Blue solid: annual total precipitation in millimetres, linear trend $+45$ mm per decade. Red dashed: count of days with daily total above 10 mm, scaled by 50 for visual comparability, linear trend $+1.15$ days per decade. Dotted lines are OLS trend fits. Both indices rise over the period.", fig.alt = "A line chart showing two time series from 1950 to 2024 for New York Central Park. The blue solid line is annual total precipitation in millimetres, rising from around 1000 millimetres at the start of the period to around 1300 by the end. The red dashed line is the count of days per year with total precipitation above 10 millimetres, also rising over time. Dotted regression lines overlay each series, both sloping upward."----
knitr::include_graphics("figures/fig2_precip.pdf")


## ----spi, fig.cap = "Twelve-month Standardised Precipitation Index for New York Central Park, 1950 to 2024. Computed with \\texttt{ck\\_spi(scale = 12)} on the full GHCND USW00094728 daily precipitation record. Dashed horizontal lines at plus and minus one mark the moderate drought and moderate wet thresholds. The 1960s Northeast drought (1962 to 1966) and 2001 to 2002 drought are the two deepest dry episodes; 2011 is the wettest year in the sample.", fig.alt = "A column chart of 12-month SPI values at monthly resolution for New York Central Park, 1950 to 2024. Columns below zero are coloured red and represent dry anomalies; columns above zero are coloured blue and represent wet anomalies. A sustained run of red columns between 1962 and 1966 reaches values around minus 2.3, labelled as the 1960s Northeast drought. Another deep red cluster around 2001 to 2002 is labelled. The deepest blue column, around 2011, reaches about plus 2.9 and is labelled as a wet year."----
knitr::include_graphics("figures/fig5_heat.pdf")


## ----huglin, fig.cap = "Huglin heliothermal index on a 10-year synthetic temperate site at latitude 51.5 degrees north. Shaded horizontal bands mark approximate viticultural suitability ranges: below 1500 is too cool, 1500 to 1800 is Cool, 1800 to 2100 is Temperate, 2100 to 2400 is Warm, above 2400 is Hot. The sample falls mostly in the Cool range.", fig.alt = "A line chart of the Huglin heliothermal index across 10 years of a synthetic temperate site. Values fluctuate between about 1550 and 1620, sitting inside a shaded horizontal band labelled Cool. Bands above and below mark Temperate, Warm, Hot, and Too cool ranges."----
knitr::include_graphics("figures/fig4_huglin.pdf")


## ----central-park, fig.cap = "Three temperature indices for New York Central Park (GHCND station USW00094728), 1950 to 2024. Annual counts from raw daily $T_{\\min}$, $T_{\\max}$, and $T_{\\mathrm{mean}}$. Blue solid: frost days ($T_{\\min} < 0^\\circ$C), linear trend $-2.6$ days per decade. Red dashed: summer days ($T_{\\max} \\geq 25^\\circ$C), trend $+0.3$ days per decade. Green dotdash: growing degree days above base $10^\\circ$C, divided by 20 for visual scale, trend $+28$ GDD per decade. Dotted lines are OLS trend fits.", fig.alt = "A line chart showing three annual temperature-index series for New York Central Park, 1950 to 2024. A blue solid line for frost days falls from about 130 per year in the 1950s to about 100 by the 2020s. A red dashed line for summer days is roughly flat around 45 per year. A green dotdash line for growing degree days (divided by 20) rises from about 80 in the 1950s to about 110 by the 2020s. Thin dotted lines show the linear trend fitted to each series."----
knitr::include_graphics("figures/fig6_central_park.pdf")

